version: '3.8'
services:
  
  nginx:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - published: 25565
        target: 25565
        protocol: tcp
    depends_on:
      waterfall:
        condition: service_started
    networks:
      - default

  mariadb:
    container_name: mariadb
    image: mariadb:10.9
    volumes:
      - type: bind
        source: ./mariadb/data
        target: /var/lib/mysql
      - type: bind
        source: ./mariadb/init
        target: /docker-entrypoint-initdb.d
    environment:
      TZ: Asia/Tokyo
    env_file:
      - ./mariadb/.env
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --performance-schema=false --expire_logs_days=1
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - internal

  redis:
    container_name: redis
    image: redis:7-alpine
    volumes:
      - type: bind
        source: ./redis
        target: /data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 30
    networks:
      - internal

  waterfall:
    container_name: waterfall
    image: ghcr.io/2mug1/waterfall:latest
    volumes:
      - type: bind
        source: ./waterfall
        target: /app
    tty: true
    stdin_open: true
    environment:
      TZ: Asia/Tokyo
      JAVA_OPTS: -Xms256M -Xmx512M
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - internal
      - default

  paper:
    container_name: paper
    image: ghcr.io/2mug1/paper:latest
    volumes:
      - type: bind
        source: ./paper
        target: /app
    tty: true
    stdin_open: true
    environment:
      TZ: Asia/Tokyo
      JAVA_OPTS: -Xms1G -Xmx2G
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - default
      - internal

networks:
  internal:
    internal: true
